baseURL = 'https://example.com/'
relativeURLs = false
theme = 'hugo-theme-relearn'

######################### Menu ###################################
[menu]
[[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-tags'></i> Tags"
    url = '/tags'
[[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-layer-group'></i> Categories"
    url = '/categories'
[[menu.shortcuts]]
    identifier = 'ds'
    name = "<i class='fa-fw fab fa-github'></i> Relearn theme repo"
    url = 'https://github.com/McShelby/hugo-theme-relearn'
    weight = 10

######################### Params ###################################
[params]
  customMathJaxURL = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js'
  disableMathJax = false
  editURL = 'https://github.com/taoli2014/hugo_blog/edit/master/content/${FilePath}'
  images = ['images/hero.png']
  mathJaxInitialize = '{ "chtml": { "displayAlign": "left" } }'
  titleSeparator = '::'
  themeVariant = ['relearn-light', 'relearn-dark']

[params.author]
    name = 'Li'

######################### Outputs ###################################
[outputs]
  home = ['html', 'rss', 'search', 'searchpage']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']


######################### Markup ###################################
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
